version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python3 backend/manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: